# Generated by Django 3.2 on 2021-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
