# Generated by Django 3.2 on 2021-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='together',
            field=models.BooleanField(null=True, verbose_name='hommes et femmes'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(related_name='article_genre', to='service.Genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='man',
            field=models.BooleanField(verbose_name='hommes'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='woman',
            field=models.BooleanField(verbose_name='femmes'),
        ),
    ]
