# Generated by Django 3.2 on 2021-05-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_genre_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriearticle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_article', to='service.groupcategorie', verbose_name='groupe'),
            preserve_default=False,
        ),
    ]
