# Generated by Django 3.2 on 2021-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_categoriearticle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='man',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='woman',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('H', 'hommes'), ('F', 'femmes'), ('HF', 'all')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
